# Generated by Django 6.0.5 on 2026-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0003_herosection_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Headline'),
        ),
    ]
