# Generated by Django 6.0.5 on 2026-05-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Amount')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sale Amount')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Profit')),
                ('agency_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Agency Commission')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ('id',),
            },
        ),
    ]
