# Generated by Django 6.0.5 on 2026-05-19 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rate')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='finance.currency', verbose_name='Base Currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='finance.currency', verbose_name='Target Currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ('-last_updated',),
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'target_currency'), name='unique_exchange_rate_pair')],
            },
        ),
    ]
