# Generated by Django 6.0.5 on 2026-05-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
    ]
