# Generated by Django 6.0.5 on 2026-05-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=100, unique=True, verbose_name='Reservation Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY')], default='EUR', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ON_PROCESS', 'On Process'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='agencies.agency', verbose_name='Agency')),
                ('tour_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='inventory.tourpackage', verbose_name='Tour Package')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Check-in Date')),
                ('check_out_date', models.DateField(verbose_name='Check-out Date')),
                ('board_type', models.CharField(choices=[('BB', 'BB'), ('HB', 'HB'), ('ALL', 'ALL')], default='BB', max_length=10, verbose_name='Board Type')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_bookings', to='inventory.hotel', verbose_name='Hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'ordering': ('check_in_date',),
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, verbose_name='Sex')),
                ('age_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('INFANT', 'Infant')], max_length=10, verbose_name='Age Type')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourists', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Tourist',
                'verbose_name_plural': 'Tourists',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100, verbose_name='Ticket Number')),
                ('pnr_code', models.CharField(blank=True, max_length=50, verbose_name='PNR Code')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_tickets', to='inventory.flight', verbose_name='Flight')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_tickets', to='reservations.reservation', verbose_name='Reservation')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_tickets', to='reservations.tourist', verbose_name='Tourist')),
            ],
            options={
                'verbose_name': 'Flight Ticket',
                'verbose_name_plural': 'Flight Tickets',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ExcursionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField(verbose_name='Tour Date')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='Pickup Time')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursion_bookings', to='inventory.excursion', verbose_name='Excursion')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_bookings', to='reservations.reservation', verbose_name='Reservation')),
                ('tourists', models.ManyToManyField(related_name='excursion_bookings', to='reservations.tourist', verbose_name='Tourists')),
            ],
            options={
                'verbose_name': 'Excursion Booking',
                'verbose_name_plural': 'Excursion Bookings',
                'ordering': ('tour_date',),
            },
        ),
    ]
