# Generated by Django 6.0.5 on 2026-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth of the tourist, if available.', null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality of the tourist, if available.', max_length=100, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='passport_expiry_date',
            field=models.DateField(blank=True, help_text='Passport expiry date of the tourist, if available.', null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Passport number of the tourist, if available.', max_length=50, verbose_name='Passport Number'),
        ),
    ]
