# Generated by Django 6.0.5 on 2026-05-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('inventory', '0005_hotel_currency'),
        ('reservations', '0003_tourist_birth_date_tourist_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('on_arrival', models.BooleanField(default=False, verbose_name='On Arrival')),
                ('on_departure', models.BooleanField(default=False, verbose_name='On Departure')),
                ('from_location_type', models.CharField(choices=[('AIRPORT', 'Airport'), ('TERMINAL', 'Terminal'), ('HOTEL', 'Hotel')], max_length=20, verbose_name='From Location Type')),
                ('from_location_name', models.CharField(max_length=255, verbose_name='From Location Name')),
                ('to_location_type', models.CharField(choices=[('AIRPORT', 'Airport'), ('TERMINAL', 'Terminal'), ('HOTEL', 'Hotel')], max_length=20, verbose_name='To Location Type')),
                ('to_location_name', models.CharField(max_length=255, verbose_name='To Location Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('external_note', models.TextField(blank=True, verbose_name='External Note')),
                ('driver_note', models.TextField(blank=True, verbose_name='Driver Note')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_services', to='finance.currency', verbose_name='Currency')),
                ('passengers', models.ManyToManyField(related_name='transfer_services', to='reservations.tourist', verbose_name='Passengers')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_services', to='reservations.reservation', verbose_name='Reservation')),
                ('tour_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_services', to='inventory.tourpackage', verbose_name='Tour Package')),
            ],
            options={
                'verbose_name': 'Transfer Service',
                'verbose_name_plural': 'Transfer Services',
                'ordering': ('service_date', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('on_arrival', True), ('on_departure', True), _connector='OR'), name='transfer_at_least_one_direction')],
            },
        ),
    ]
