# Generated by Django 6.0.5 on 2026-05-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_email_agency_icq_agency_mobile_phone_and_more'),
        ('reservations', '0004_transferservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='agencies.agency', verbose_name='Agency'),
        ),
    ]
