# Generated by Django 6.0.5 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferservice',
            name='agency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agency Price'),
        ),
    ]
