# Generated by Django 6.0.5 on 2026-05-30 09:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('inventory', '0008_flight_agency_price_hotel_agency_price'),
        ('reservations', '0006_transferservice_agency_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_date', models.DateTimeField(auto_now_add=True, verbose_name='System Date')),
                ('excursion_date', models.DateField(verbose_name='Excursion Date')),
                ('is_combo', models.BooleanField(default=False, verbose_name='Is Combo')),
                ('pickup_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pickup Point')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Price')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cost')),
                ('cross_currency_rate', models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), max_digits=15, verbose_name='Cross Currency Rate')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('confirm_booking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Booking Number')),
                ('agent_confirmation_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Agent Confirmation Number')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('cost_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursion_services_cost', to='finance.currency', verbose_name='Cost Currency')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursion_services', to='inventory.excursion', verbose_name='Excursion')),
                ('selling_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursion_services_selling', to='finance.currency', verbose_name='Selling Currency')),
            ],
            options={
                'verbose_name': 'Excursion Service',
                'verbose_name_plural': 'Excursion Services',
                'ordering': ('-excursion_date',),
            },
        ),
    ]
