# Generated by Django 6.0.5 on 2026-05-30 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transferprovider_transfer'),
        ('reservations', '0007_excursionservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferservice',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='inventory.transfer', verbose_name='Transfer (Catalog)'),
        ),
    ]
