# Generated by Django 6.0.5 on 2026-06-06 09:41

import django.db.models.deletion
from django.db import migrations, models


def delete_existing_hotel_bookings(apps, schema_editor):
    HotelBooking = apps.get_model('reservations', 'HotelBooking')
    HotelBooking.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_hotel_agency_price_remove_hotel_cost_price_and_more'),
        ('reservations', '0008_transferservice_transfer'),
    ]

    operations = [
        migrations.RunPython(delete_existing_hotel_bookings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='board_type',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_bookings', to='inventory.hotelroom', verbose_name='Hotel Room'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
