# Generated by Django 6.0.5 on 2026-06-06 12:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('reservations', '0009_remove_hotelbooking_board_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='agency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agency Price'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='agent_confirmation_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Agent Confirmation Number'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='confirm_booking_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Confirm Booking Number'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cost_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotel_bookings_cost', to='finance.currency', verbose_name='Cost Currency'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cross_currency_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), max_digits=15, verbose_name='Cross Currency Rate'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_cancellation_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hotel Cancellation Number'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='Internal Note'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='remarks_for_hotel',
            field=models.TextField(blank=True, verbose_name='Remarks for Hotel'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='selling_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotel_bookings_selling', to='finance.currency', verbose_name='Selling Currency'),
        ),
    ]
