# Generated by Django 6.0.5 on 2026-06-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_add_hotel_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='tourists',
            field=models.ManyToManyField(blank=True, related_name='hotel_bookings', to='reservations.tourist', verbose_name='Tourists'),
        ),
    ]
