# Generated by Django 6.0.5 on 2026-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_hotelbooking_tourists'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_locked_by_finance',
            field=models.BooleanField(default=False, help_text='When true, only Finance/Admin users can modify this reservation. Sales/Reservation staff get read-only access.', verbose_name='Locked by Finance'),
        ),
    ]
