# Generated by Django 6.0.5 on 2026-06-14 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservation_is_locked_by_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('FINANCE_LOCKED', 'Finance Locked'), ('FINANCE_UNLOCKED', 'Finance Unlocked'), ('TOURIST_ADDED', 'Tourist Added'), ('HOTEL_BOOKING_ADDED', 'Hotel Booking Added'), ('HOTEL_BOOKING_UPDATED', 'Hotel Booking Updated'), ('FLIGHT_TICKET_ADDED', 'Flight Ticket Added'), ('TRANSFER_SERVICE_ADDED', 'Transfer Service Added'), ('EXCURSION_BOOKING_ADDED', 'Excursion Booking Added'), ('EXCURSION_SERVICE_ADDED', 'Excursion Service Added')], max_length=50, verbose_name='Action')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Reservation Activity Log',
                'verbose_name_plural': 'Reservation Activity Logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['reservation', '-created_at'], name='reservation_reserva_bb9f1b_idx'), models.Index(fields=['actor', '-created_at'], name='reservation_actor_i_986718_idx'), models.Index(fields=['action'], name='reservation_action_bb6060_idx')],
            },
        ),
    ]
