# Generated by Django 6.0.5 on 2026-06-20 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_reservationactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The internal staff member currently responsible for handling this reservation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
    ]
