# Generated by Django 6.0.5 on 2026-07-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('reservations', '0015_reservation_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_tickets', to='finance.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
    ]
