# Generated by Django 6.0.5 on 2026-07-12 11:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('reservations', '0016_add_flight_ticket_financial_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_date', models.DateTimeField(auto_now_add=True, verbose_name='System Date')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('service_name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('cross_currency_rate', models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), max_digits=15, verbose_name='Cross Currency Rate')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cost')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_services_cost', to='finance.currency', verbose_name='Cost Currency')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_services', to='reservations.reservation', verbose_name='Reservation')),
                ('selling_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_services_selling', to='finance.currency', verbose_name='Selling Currency')),
            ],
            options={
                'verbose_name': 'Other Service',
                'verbose_name_plural': 'Other Services',
                'ordering': ('-system_date',),
            },
        ),
    ]
