# Generated by Django 6.0.5 on 2026-07-13 13:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('reservations', '0017_add_other_service_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferservice',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='cost_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_services_cost', to='finance.currency', verbose_name='Cost Currency'),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='cross_currency_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), max_digits=15, verbose_name='Cross Currency Rate'),
        ),
    ]
