# Generated by Django 6.0.5 on 2026-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_add_flight_ticket_cost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='arrival_city_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arrival City Name'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='arrival_flight_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arrival Flight Number'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='arrival_terminal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arrival Terminal'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='departure_city_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departure City Name'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='departure_flight_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departure Flight Number'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='departure_terminal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departure Terminal'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email of the tourist, if available.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='iin',
            field=models.CharField(blank=True, help_text='National ID / tax number of the tourist, if available.', max_length=255, null=True, verbose_name='IIN'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Insurance'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='issue_city',
            field=models.CharField(blank=True, help_text='City where the passport was issued, if available.', max_length=255, null=True, verbose_name='Issue City'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='passport_issue_date',
            field=models.DateField(blank=True, help_text='Passport issue date of the tourist, if available.', null=True, verbose_name='Passport Issue Date'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'ID Card'), ('OTHER', 'Other')], help_text='Type of identity document presented, if available.', max_length=50, null=True, verbose_name='Passport Type'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number of the tourist, if available.', max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='policy_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Policy End Date'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Policy Number'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='policy_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Policy Start Date'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourcode_confirmation_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TourCode Confirmation Number'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=10, verbose_name='Sex'),
        ),
    ]
