# Generated by Django 6.0.5 on 2026-08-23 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_tourist_arrival_city_name_tourist_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionservice',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excursion_services', to='reservations.reservation', verbose_name='Reservation'),
        ),
    ]
