# Generated by Django 6.0.5 on 2026-09-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_supplier'),
        ('reservations', '0022_reservation_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionservice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_services', to='agencies.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_tickets', to='agencies.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to='agencies.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_services', to='agencies.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_services', to='agencies.supplier', verbose_name='Supplier'),
        ),
    ]
