# Generated by Django 6.0.5 on 2026-09-05 10:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_excursionservice_supplier_flightticket_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionservice',
            name='cost_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to cost. Total cost = cost + cost correction.', max_digits=10, verbose_name='Cost Correction'),
        ),
        migrations.AddField(
            model_name='excursionservice',
            name='price_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to price. Total price = price + price correction.', max_digits=10, verbose_name='Price Correction'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='cost_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to cost. Total cost = cost + cost correction.', max_digits=12, verbose_name='Cost Correction'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='price_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to price. Total price = price + price correction.', max_digits=12, verbose_name='Price Correction'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cost_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to cost. Total cost = cost + cost correction.', max_digits=12, verbose_name='Cost Correction'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='price_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to price. Total price = price + price correction.', max_digits=12, verbose_name='Price Correction'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='cost_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to cost. Total cost = cost + cost correction.', max_digits=12, verbose_name='Cost Correction'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='price_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to price. Total price = price + price correction.', max_digits=12, verbose_name='Price Correction'),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='cost_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to cost. Total cost = cost + cost correction.', max_digits=12, verbose_name='Cost Correction'),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='price_correction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to price. Total price = price + price correction.', max_digits=12, verbose_name='Price Correction'),
        ),
        migrations.CreateModel(
            name='ServicePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('HOTEL', 'Hotel Booking'), ('TRANSFER', 'Transfer Service'), ('FLIGHT', 'Flight Ticket'), ('OTHER', 'Other Service'), ('EXCURSION', 'Excursion Service')], max_length=20, verbose_name='Service Type')),
                ('service_id', models.PositiveIntegerField(verbose_name='Service ID')),
                ('field_name', models.CharField(choices=[('PRICE', 'Price'), ('COST', 'Cost'), ('PRICE_CORRECTION', 'Price Correction'), ('COST_CORRECTION', 'Cost Correction')], max_length=20, verbose_name='Field Name')),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Old Value')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='New Value')),
                ('currency_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Currency Code')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('is_reverted', models.BooleanField(default=False, verbose_name='Is Reverted')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='reservations.reservation', verbose_name='Reservation')),
                ('reverted_from', models.ForeignKey(blank=True, help_text='If this entry was created by an undo, points to the entry it reverted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revert_entries', to='reservations.servicepricehistory', verbose_name='Reverted From')),
            ],
            options={
                'verbose_name': 'Service Price History',
                'verbose_name_plural': 'Service Price History',
                'ordering': ('-changed_at',),
                'indexes': [models.Index(fields=['service_type', 'service_id'], name='reservation_service_286df4_idx'), models.Index(fields=['reservation', '-changed_at'], name='reservation_reserva_f7972a_idx')],
            },
        ),
    ]
