# Generated by Django 6.0.5 on 2026-05-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
        ('agencies', '0002_agency_email_agency_icq_agency_mobile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='agencies.agency', verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('NORMAL', 'Normal User'), ('AGENCY', 'Agency'), ('STAFF', 'Staff')], default='NORMAL', max_length=20, verbose_name='Role'),
        ),
    ]
