# Generated by Django 6.0.5 on 2026-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('NORMAL', 'Normal User'), ('AGENCY', 'Agency'), ('ADMIN', 'Admin'), ('SALES', 'Sales Staff'), ('RESERVATION', 'Reservation Manager'), ('INVENTORY', 'Inventory/Admin Staff'), ('FINANCE', 'Finance/Accounting')], default='NORMAL', max_length=20, verbose_name='Role'),
        ),
    ]
