# Generated by Django 6.0.5 on 2026-09-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('RESERVATION', 'Reservation Department'), ('ACCOUNTS', 'Accounts Department'), ('SALES', 'Sales Department'), ('OPERATIONS', 'Operations Department'), ('INVENTORY', 'Inventory Department'), ('MANAGEMENT', 'Management')], max_length=20, null=True, verbose_name='Department'),
        ),
    ]
