# Generated by Django 6.0.5 on 2026-07-29 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Default Email Config', help_text='Friendly name for this configuration', max_length=100)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('from_email', models.EmailField(help_text='The "From" address shown on outgoing emails', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', help_text='Display name shown alongside the from address', max_length=100)),
                ('encryption', models.CharField(choices=[('TLS', 'TLS (STARTTLS)'), ('SSL', 'SSL/TLS'), ('NONE', 'None')], default='TLS', max_length=4)),
                ('is_active', models.BooleanField(default=True, help_text='Only one config should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
