# Generated by Django 6.0.5 on 2026-07-29 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_settings', '0001_initial'),
        ('reservations', '0019_add_flight_ticket_cost_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('SENT', 'Sent')], default='SENT', max_length=4)),
                ('to_address', models.CharField(max_length=255)),
                ('cc_address', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='reservations.reservation', verbose_name='Reservation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reservation_emails', to=settings.AUTH_USER_MODEL, verbose_name='Sent By')),
            ],
            options={
                'verbose_name': 'Reservation Email',
                'verbose_name_plural': 'Reservation Emails',
                'ordering': ('-sent_at',),
            },
        ),
    ]
