# Generated by Django 6.0.5 on 2026-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Excursion Name')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Duration (Hours)')),
            ],
            options={
                'verbose_name': 'Excursion',
                'verbose_name_plural': 'Excursions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50, verbose_name='Flight Number')),
                ('airline', models.CharField(max_length=120, verbose_name='Airline')),
                ('origin', models.CharField(max_length=120, verbose_name='Origin')),
                ('destination', models.CharField(max_length=120, verbose_name='Destination')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival Time')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ('-departure_time',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('stars', models.IntegerField(verbose_name='Stars')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Package Name')),
                ('destination', models.CharField(max_length=120, verbose_name='Destination')),
                ('days', models.IntegerField(verbose_name='Days')),
                ('nights', models.IntegerField(verbose_name='Nights')),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ('name',),
            },
        ),
    ]
