# Generated by Django 6.0.5 on 2026-05-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='city_en',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='city_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='city_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Excursion Name'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Excursion Name'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Excursion Name'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_en',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Hotel Name'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Hotel Name'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Hotel Name'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='destination_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='destination_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='destination_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Package Name'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Package Name'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Package Name'),
        ),
    ]
