# Generated by Django 6.0.5 on 2026-05-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_currency_name_en_currency_name_ru_currency_name_tr"),
        ("inventory", "0002_excursion_city_en_excursion_city_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="finance.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Price"),
        ),
    ]
