# Generated by Django 6.0.5 on 2026-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_flight_currency_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Price"),
        ),
    ]
