# Generated by Django 6.0.5 on 2026-05-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_currency_name_en_currency_name_ru_currency_name_tr"),
        ("inventory", "0004_hotel_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hotels",
                to="finance.currency",
                verbose_name="Currency",
            ),
        ),
    ]
