# Generated by Django 6.0.5 on 2026-05-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('inventory', '0005_hotel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='agency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agency Price'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_packages', to='finance.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='public_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Public Price'),
        ),
    ]
