# Generated by Django 6.0.5 on 2026-05-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_tourpackage_agency_price_tourpackage_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Feature Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Feature Name')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Feature Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Feature Name')),
            ],
            options={
                'verbose_name': 'Hotel Feature',
                'verbose_name_plural': 'Hotel Features',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/main/', verbose_name='Main Image'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='inventory.hotelfeature', verbose_name='Features'),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/', verbose_name='Gallery Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='inventory.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Gallery Image',
                'verbose_name_plural': 'Hotel Gallery Images',
                'ordering': ('order', 'id'),
            },
        ),
    ]
