# Generated by Django 6.0.5 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_hotelfeature_hotel_description_hotel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='agency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agency Price'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='agency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agency Price'),
        ),
    ]
