# Generated by Django 6.0.5 on 2026-05-30 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('inventory', '0009_excursion_agency_price_excursion_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Provider Name')),
                ('provider_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual')], default='COMPANY', max_length=20, verbose_name='Provider Type')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Transfer Provider',
                'verbose_name_plural': 'Transfer Providers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Transfer Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Transfer Name')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='Transfer Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Transfer Name')),
                ('from_location', models.CharField(max_length=255, verbose_name='From Location')),
                ('from_location_en', models.CharField(max_length=255, null=True, verbose_name='From Location')),
                ('from_location_tr', models.CharField(max_length=255, null=True, verbose_name='From Location')),
                ('from_location_ru', models.CharField(max_length=255, null=True, verbose_name='From Location')),
                ('to_location', models.CharField(max_length=255, verbose_name='To Location')),
                ('to_location_en', models.CharField(max_length=255, null=True, verbose_name='To Location')),
                ('to_location_tr', models.CharField(max_length=255, null=True, verbose_name='To Location')),
                ('to_location_ru', models.CharField(max_length=255, null=True, verbose_name='To Location')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, verbose_name='Vehicle Type')),
                ('vehicle_type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Type')),
                ('vehicle_type_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Type')),
                ('vehicle_type_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Type')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('public_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Public Price')),
                ('agency_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agency Price')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='finance.currency', verbose_name='Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.transferprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ('name',),
            },
        ),
    ]
