# Generated by Django 6.0.5 on 2026-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transferprovider_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal procurement cost paid by Jovira. Not visible to agencies or public.', max_digits=12, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='flight',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal procurement cost paid by Jovira. Not visible to agencies or public.', max_digits=12, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal procurement cost paid by Jovira. Not visible to agencies or public.', max_digits=12, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal procurement cost paid by Jovira. Not visible to agencies or public.', max_digits=12, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal procurement cost paid by Jovira. Not visible to agencies or public.', max_digits=12, null=True, verbose_name='Cost Price'),
        ),
    ]
