# Generated by Django 6.0.5 on 2026-06-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_excursion_cost_price_flight_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='excursions',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='inventory.excursion', verbose_name='Excursions'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='inventory.flight', verbose_name='Flights'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='inventory.hotel', verbose_name='Hotels'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='transfers',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='inventory.transfer', verbose_name='Transfers'),
        ),
    ]
