# Generated by Django 6.0.5 on 2026-06-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
        ('inventory', '0012_tourpackage_excursions_tourpackage_flights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='agency_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('FAMILY', 'Family'), ('SUITE', 'Suite')], max_length=20, verbose_name='Room Type')),
                ('board_type', models.CharField(choices=[('RO', 'RO (Room Only)'), ('BB', 'BB (Bed & Breakfast)'), ('HB', 'HB (Half Board)'), ('FB', 'FB (Full Board)'), ('ALL', 'All Inclusive'), ('UALL', 'Ultra All Inclusive')], max_length=10, verbose_name='Board Type')),
                ('date_from', models.DateField(verbose_name='Date From')),
                ('date_to', models.DateField(verbose_name='Date To')),
                ('availability_count', models.PositiveIntegerField(default=0, verbose_name='Availability Count')),
                ('public_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Public Price')),
                ('agency_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agency Price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Internal procurement cost paid by Jovira. Not visible to agencies or public.', max_digits=12, null=True, verbose_name='Cost Price')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('note_en', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('note_tr', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('note_ru', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_rooms', to='finance.currency', verbose_name='Currency')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Room',
                'verbose_name_plural': 'Hotel Rooms',
                'ordering': ('hotel', 'date_from', 'room_type'),
            },
        ),
    ]
