# Generated by Django 6.0.5 on 2026-08-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_hotel_agency_price_remove_hotel_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_packages/main/', verbose_name='Main Image'),
        ),
        migrations.CreateModel(
            name='TourPackageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_packages/gallery/', verbose_name='Gallery Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='inventory.tourpackage', verbose_name='Tour Package')),
            ],
            options={
                'verbose_name': 'Tour Package Gallery Image',
                'verbose_name_plural': 'Tour Package Gallery Images',
                'ordering': ('order', 'id'),
            },
        ),
    ]
