# Generated by Django 6.0.5 on 2026-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='agency',
            name='icq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ICQ'),
        ),
        migrations.AddField(
            model_name='agency',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='agency',
            name='skype_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Skype ID'),
        ),
    ]
