# Generated by Django 6.0.5 on 2026-09-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_approval_fields'),
        ('finance', '0004_currency_name_en_currency_name_ru_currency_name_tr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('supplier_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('TRANSFER', 'Transfer Company'), ('TOUR_OPERATOR', 'Tour Operator'), ('AIRLINE', 'Airline'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Supplier Type')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('tax_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Tax Number')),
                ('bank_details', models.TextField(blank=True, default='', verbose_name='Bank Details')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='finance.currency', verbose_name='Default Currency')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ('name',),
            },
        ),
    ]
